name: Deploy to VPS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          composer install --no-dev

      - name: Deploy to VPS
        run: |
          rsync -avz --exclude '.git/' --exclude '.github/' --exclude 'wp-config.php' ./ user@your-vps-ip:/path/to/wordpress/
