name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          VPSKEY: ${{ secrets.VPSKEY }}
        run: |
          ssh-keyscan -H your-vps-ip >> ~/.ssh/known_hosts
          ssh -i $VPSKEY user@your-vps-ip << 'EOF'
            cd /var/www/html/
            git pull origin main
            # Thêm các lệnh khác bạn cần thiết để triển khai
          EOF
