name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPSKEY }}  # Sử dụng secret có tên VPSKEY

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H your-vps-ip >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh user@your-vps-ip << 'EOF'
            cd /var/www/html/
            git pull origin main
            # Thêm các lệnh khác bạn cần thiết để triển khai
          EOF
